/**
 * Chapter metadata and data for the Constitution of Malta
 */
import type { Chapter } from "../models";

export const CHAPTERS: Chapter[] = [
  {
    chapter: "1",
    title: "The Republic of Malta",
    description:
      "Malta's core identity as a peaceful, independent republic built on democratic values and Catholic heritage",
    tags: [
      "democracy",
      "republic",
      "sovereignty",
      "neutrality",
      "religion",
      "symbols",
      "Malta",
      "independence",
      "state",
      "nation",
      "Catholic",
      "identity",
      "peaceful",
      "democratic values",
      "national identity",
      "constitutional foundations",
      "republicanism",
    ],
    heroImage: "/images/chapters/1.webp",
    articleCount: 6,
  },
  {
    chapter: "2",
    title: "Declaration of Principles",
    description:
      "Malta's social commitments and guiding principles that shape policies and future laws",
    tags: [
      "principles",
      "social",
      "work",
      "employment",
      "equality",
      "sustainability",
      "social policy",
      "guiding principles",
      "commitments",
      "social justice",
      "welfare",
      "environment",
      "sustainable development",
      "social democracy",
      "workers rights",
      "social protection",
      "public policy",
      "social cohesion",
    ],
    heroImage: "/images/chapters/2.webp",
    articleCount: 15,
  },
  {
    chapter: "3",
    title: "Citizenship",
    description:
      "How Maltese citizenship is regulated and treatment of Commonwealth and Irish citizens",
    tags: [
      "citizenship",
      "nationality",
      "commonwealth",
      "immigration",
      "legal status",
      "naturalization",
      "birth right",
      "Irish citizens",
      "Commonwealth citizens",
      "citizen rights",
      "nationality law",
      "passport",
      "residency",
      "dual citizenship",
      "citizenship acquisition",
      "legal identity",
      "migration",
    ],
    heroImage: "/images/chapters/3.webp",
    articleCount: 4,
  },
  {
    chapter: "4",
    title: "Fundamental Rights and Freedoms",
    description:
      "The cornerstone of Malta's constitutional democracy guaranteeing civil liberties and basic freedoms",
    tags: [
      "rights",
      "freedoms",
      "liberty",
      "civil rights",
      "human rights",
      "democracy",
      "justice",
      "equality",
      "privacy",
      "expression",
      "assembly",
      "fundamental freedoms",
      "constitutional rights",
      "civil liberties",
      "freedom of speech",
      "freedom of religion",
      "freedom of movement",
      "due process",
      "equal treatment",
      "non-discrimination",
      "personal liberty",
      "property rights",
      "fair trial",
      "habeas corpus",
    ],
    heroImage: "/images/chapters/4.webp",
    articleCount: 16,
  },
  {
    chapter: "5",
    title: "The President of Malta",
    description:
      "The office of the President, appointment process, duties and constitutional role in democratic functions",
    tags: [
      "president",
      "head of state",
      "appointment",
      "ceremonial",
      "unity",
      "constitutional monarchy",
      "executive",
      "state functions",
      "presidential duties",
      "head of state powers",
      "constitutional role",
      "national unity",
      "ceremonial functions",
      "state visits",
      "appointments",
      "constitutional guardian",
    ],
    heroImage: "/images/chapters/5.webp",
    articleCount: 8,
  },
  {
    chapter: "6",
    title: "Parliament",
    description:
      "The legislative branch of government, parliamentary procedures and democratic representation",
    tags: [
      "parliament",
      "legislative",
      "democracy",
      "representation",
      "elections",
      "MPs",
      "House of Representatives",
      "legislative process",
      "parliamentary democracy",
      "electoral system",
      "constituencies",
      "legislation",
      "parliamentary procedure",
      "lawmaking",
      "democratic representation",
      "parliamentary sovereignty",
      "bills",
      "acts of parliament",
      "parliamentary sessions",
      "Speaker",
      "parliamentary committees",
    ],
    heroImage: "/images/chapters/6.webp",
    articleCount: 12,
  },
  {
    chapter: "7",
    title: "Executive Power",
    description:
      "How executive authority is exercised through symbolic leadership, practical governance and legal accountability",
    tags: [
      "executive",
      "government",
      "prime minister",
      "cabinet",
      "governance",
      "Prime Minister",
      "Cabinet",
      "ministers",
      "executive authority",
      "government administration",
      "public administration",
      "executive decisions",
      "cabinet collective responsibility",
      "ministerial responsibility",
      "government departments",
      "public service",
      "policy implementation",
      "executive leadership",
    ],
    heroImage: "/images/chapters/7.webp",
    articleCount: 10,
  },
  {
    chapter: "8",
    title: "The Judiciary",
    description:
      "A pillar of democratic governance ensuring judicial independence, accountability and fairness",
    tags: [
      "judiciary",
      "courts",
      "judges",
      "justice",
      "independence",
      "rule of law",
      "legal system",
      "judicial review",
      "magistrates",
      "judicial independence",
      "court system",
      "judicial appointments",
      "constitutional court",
      "supreme court",
      "civil courts",
      "criminal courts",
      "judicial accountability",
      "access to justice",
      "fair trial",
      "judicial process",
      "legal proceedings",
    ],
    heroImage: "/images/chapters/8.webp",
    articleCount: 8,
  },
  {
    chapter: "9",
    title: "Finance",
    description:
      "Managing public funds transparently through constitutional controls and parliamentary oversight",
    tags: [
      "finance",
      "budget",
      "public funds",
      "transparency",
      "oversight",
      "public finance",
      "government spending",
      "taxation",
      "public money",
      "financial accountability",
      "auditing",
      "parliamentary control",
      "public accounts",
      "financial management",
      "treasury",
      "government revenue",
      "fiscal responsibility",
      "public expenditure",
      "consolidated fund",
    ],
    heroImage: "/images/chapters/9.webp",
    articleCount: 6,
  },
  {
    chapter: "10",
    title: "The Public Service",
    description:
      "Appointment, oversight and pension rights for Malta's civil service and public sector employees",
    tags: [
      "public service",
      "civil service",
      "employment",
      "pensions",
      "oversight",
      "public servants",
      "government employees",
      "public sector",
      "civil servants",
      "public administration",
      "merit-based appointments",
      "public service commission",
      "employment conditions",
      "retirement benefits",
      "public sector employment",
      "administrative service",
      "government workforce",
    ],
    heroImage: "/images/chapters/10.webp",
    articleCount: 5,
  },
  {
    chapter: "10A",
    title: "Local Councils",
    description:
      "Local government structure and the role of councils in Malta's democratic governance",
    tags: [
      "local government",
      "councils",
      "municipalities",
      "local democracy",
      "local authorities",
      "regional government",
      "local administration",
      "community governance",
      "decentralization",
      "local services",
      "municipal services",
      "local elections",
      "mayors",
      "councillors",
      "local autonomy",
      "grassroots democracy",
      "civic participation",
    ],
    heroImage: "/images/chapters/10A.webp",
    articleCount: 4,
  },
  {
    chapter: "11",
    title: "Miscellaneous Provisions",
    description:
      "Additional constitutional provisions covering various aspects of Malta's legal framework",
    tags: [
      "miscellaneous",
      "provisions",
      "legal framework",
      "constitutional",
      "general provisions",
      "supplementary rules",
      "constitutional miscellany",
      "additional provisions",
      "constitutional details",
      "legal provisions",
      "constitutional completeness",
      "framework provisions",
      "constitutional technicalities",
    ],
    heroImage: "/images/chapters/11.webp",
    articleCount: 6,
  },
];

export const CHAPTER_ORDER = CHAPTERS.map((chapter) => chapter.chapter);
